### ISSUE TITLE
Add JUnit Reporter

### ISSUE THREAD

**Issue by wilsonodk** [turnerlabs/harbor#8]
Adding a JUnit Reporter to Mocha will allow CircleCI to show a summary of all test failures and identify our slowest tests. 

Add `mocha-junit-reporter` to our dev dependencies.

Update `circle.yml` to the the JUnit Reporter:

``` yaml
test:
  override:
    - mocha test --reporter mocha-junit-reporter:
        environment:
          MOCHA_FILE: $CIRCLE_TEST_REPORTS/junit/test-results.xml
```
